//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BalkanButton.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class bambino_dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new bambino_dbEntities object using the connection string found in the 'bambino_dbEntities' section of the application configuration file.
        /// </summary>
        public bambino_dbEntities() : base("name=bambino_dbEntities", "bambino_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new bambino_dbEntities object.
        /// </summary>
        public bambino_dbEntities(string connectionString) : base(connectionString, "bambino_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new bambino_dbEntities object.
        /// </summary>
        public bambino_dbEntities(EntityConnection connection) : base(connection, "bambino_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<log> log
        {
            get
            {
                if ((_log == null))
                {
                    _log = base.CreateObjectSet<log>("log");
                }
                return _log;
            }
        }
        private ObjectSet<log> _log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<playbacklog> playbacklog
        {
            get
            {
                if ((_playbacklog == null))
                {
                    _playbacklog = base.CreateObjectSet<playbacklog>("playbacklog");
                }
                return _playbacklog;
            }
        }
        private ObjectSet<playbacklog> _playbacklog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<song> song
        {
            get
            {
                if ((_song == null))
                {
                    _song = base.CreateObjectSet<song>("song");
                }
                return _song;
            }
        }
        private ObjectSet<song> _song;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolog(log log)
        {
            base.AddObject("log", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the playbacklog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplaybacklog(playbacklog playbacklog)
        {
            base.AddObject("playbacklog", playbacklog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the song EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosong(song song)
        {
            base.AddObject("song", song);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bambino", Name="log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new log object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static log Createlog(global::System.Int64 id)
        {
            log log = new log();
            log.id = id;
            return log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> createdOn
        {
            get
            {
                return _createdOn;
            }
            set
            {
                OncreatedOnChanging(value);
                ReportPropertyChanging("createdOn");
                _createdOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdOn");
                OncreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _createdOn;
        partial void OncreatedOnChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bambino", Name="playbacklog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class playbacklog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new playbacklog object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static playbacklog Createplaybacklog(global::System.Int64 id)
        {
            playbacklog playbacklog = new playbacklog();
            playbacklog.id = id;
            return playbacklog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> songId
        {
            get
            {
                return _songId;
            }
            set
            {
                OnsongIdChanging(value);
                ReportPropertyChanging("songId");
                _songId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("songId");
                OnsongIdChanged();
            }
        }
        private Nullable<global::System.Double> _songId;
        partial void OnsongIdChanging(Nullable<global::System.Double> value);
        partial void OnsongIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userAgent
        {
            get
            {
                return _userAgent;
            }
            set
            {
                OnuserAgentChanging(value);
                ReportPropertyChanging("userAgent");
                _userAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userAgent");
                OnuserAgentChanged();
            }
        }
        private global::System.String _userAgent;
        partial void OnuserAgentChanging(global::System.String value);
        partial void OnuserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> createdOn
        {
            get
            {
                return _createdOn;
            }
            set
            {
                OncreatedOnChanging(value);
                ReportPropertyChanging("createdOn");
                _createdOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdOn");
                OncreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _createdOn;
        partial void OncreatedOnChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Bambino", Name="song")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class song : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new song object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="free">Initial value of the free property.</param>
        public static song Createsong(global::System.Int64 id, global::System.Boolean free)
        {
            song song = new song();
            song.id = id;
            song.free = free;
            return song;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ytid
        {
            get
            {
                return _ytid;
            }
            set
            {
                OnytidChanging(value);
                ReportPropertyChanging("ytid");
                _ytid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ytid");
                OnytidChanged();
            }
        }
        private global::System.String _ytid;
        partial void OnytidChanging(global::System.String value);
        partial void OnytidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String language
        {
            get
            {
                return _language;
            }
            set
            {
                OnlanguageChanging(value);
                ReportPropertyChanging("language");
                _language = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("language");
                OnlanguageChanged();
            }
        }
        private global::System.String _language;
        partial void OnlanguageChanging(global::System.String value);
        partial void OnlanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean free
        {
            get
            {
                return _free;
            }
            set
            {
                OnfreeChanging(value);
                ReportPropertyChanging("free");
                _free = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("free");
                OnfreeChanged();
            }
        }
        private global::System.Boolean _free;
        partial void OnfreeChanging(global::System.Boolean value);
        partial void OnfreeChanged();

        #endregion

    
    }

    #endregion

    
}
