//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalkanButton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playbacklog
    {
        public long id { get; set; }
        public Nullable<double> songId { get; set; }
        public string userAgent { get; set; }
        public Nullable<System.DateTimeOffset> createdOn { get; set; }
    }
}
