//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalkanButton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public long id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string ytid { get; set; }
        public string language { get; set; }
        public bool free { get; set; }
    }
}
